#!/usr/bin/env bash
set -eu

version=3.1.2
binary="shfmt_v${version}_linux_arm"
sha256=e13cf317cc653d33e6b6d1cfe36fa891052c6211190a2ada7a46367417726c44

check_version() {
    out="$(shfmt --version 2>/dev/null)" && [ "$out" = "v$version" ]
}

if ! check_version; then
    tmpdir="$(mktemp -d)"
    trap 'rm -r "$tmpdir"' EXIT
    cd "$tmpdir"
    wget -nv "https://github.com/mvdan/sh/releases/download/v3.1.2/$binary"
    sha256sum -c <<<"$sha256 $binary"
    chmod +x "$binary"
    mv "$binary" /usr/local/bin/shfmt
    check_version
fi
