#!/usr/bin/env bash
set -eu

version=0.7.1
tarball="shellcheck-v$version.linux.armv6hf.tar.xz"
sha256=8ce0b5cd45a3e6c3d52f94958266bd894041078d2080ee6ddc22b5b313590a2e

check_version() {
    out="$(shellcheck --version 2>/dev/null)" && [[ "$out" = *"
version: $version
"* ]]
}

if ! check_version; then
    tmpdir="$(mktemp -d)"
    trap 'rm -r "$tmpdir"' EXIT
    cd "$tmpdir"
    wget -nv "https://github.com/koalaman/shellcheck/releases/download/v$version/$tarball"
    sha256sum -c <<<"$sha256 $tarball"
    tar -xJf "$tarball" --no-same-owner --strip-components=1 -C /usr/local/bin "shellcheck-v$version/shellcheck"
    check_version
fi
